spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_db
    username: root
    password: Karthik@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
server:
  port: 8082
